import { supabase } from './supabase-config.js';
const $=id=>document.getElementById(id),photos=$('photosPanel'),videos=$('videosPanel');
$('photosTab')?.addEventListener('click',()=>{photos.hidden=false;videos.hidden=true;$('photosTab').classList.add('active');$('videosTab').classList.remove('active')});
$('videosTab')?.addEventListener('click',()=>{photos.hidden=true;videos.hidden=false;$('videosTab').classList.add('active');$('photosTab').classList.remove('active')});
function yt(u){const m=u.match(/(?:youtu\.be\/|youtube\.com\/(?:watch\?v=|embed\/|shorts\/))([^?&/]+)/);return m?.[1]||null}function vm(u){const m=u.match(/vimeo\.com\/(?:video\/)?(\d+)/);return m?.[1]||null}
function thumb(v){const id=yt(v.url||'');return v.thumbnail||(id?`https://img.youtube.com/vi/${id}/hqdefault.jpg`:'assets/ctc-logo-exact.png')}
function player(u){const y=yt(u),v=vm(u);if(y)return `<iframe src="https://www.youtube.com/embed/${y}?autoplay=1" title="CTC video" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe>`;if(v)return `<iframe src="https://player.vimeo.com/video/${v}?autoplay=1" title="CTC video" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>`;return `<video src="${u}" controls autoplay playsinline></video>`}
const {data}=await supabase.from('site_settings').select('setting_value').eq('setting_key','gallery_videos').maybeSingle();let list=[];try{list=JSON.parse(data?.setting_value||'[]')}catch{}const grid=$('videoGrid');if(list.length){grid.innerHTML=list.map((v,i)=>`<button class="video-card" type="button" data-video="${i}"><span class="video-thumb"><img src="${thumb(v)}" alt="${v.title||'CTC video'}"><span class="video-play">▶</span></span><strong>${v.title||'CTC Video'}</strong><small>${v.description||''}</small></button>`).join('')}else $('videoEmpty').hidden=false;
function close(){const l=$('videoLightbox');l.hidden=true;$('videoPlayerShell').innerHTML='';document.body.classList.remove('lightbox-open')}
grid?.addEventListener('click',e=>{const b=e.target.closest('[data-video]');if(!b)return;const v=list[Number(b.dataset.video)];$('videoPlayerShell').innerHTML=player(v.url);$('videoPlayerTitle').textContent=v.title||'CTC Video';$('videoPlayerDescription').textContent=v.description||'';$('videoLightbox').hidden=false;document.body.classList.add('lightbox-open')});$('videoClose')?.addEventListener('click',close);$('videoLightbox')?.addEventListener('click',e=>{if(e.target.id==='videoLightbox')close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('videoLightbox')?.hidden)close()});