-- CTC FINAL CONTROL CENTER SETUP
-- Safe to run more than once in Supabase SQL Editor.

-- 1) Core tables
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  promotion text not null,
  event_date date not null,
  city text not null,
  state text not null,
  venue text,
  discipline text,
  status text not null default 'confirmed',
  flyer_url text,
  notes text,
  sort_order integer not null default 0,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.gallery_items (
  id bigint generated by default as identity primary key,
  image_url text not null,
  caption text,
  alt_text text,
  sort_order integer not null default 0,
  is_featured boolean not null default false,
  is_published boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.site_settings (
  id bigint generated by default as identity primary key,
  setting_key text not null unique,
  setting_value text,
  updated_at timestamptz not null default now()
);

create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  first_name text,
  last_name text,
  email text,
  phone text,
  city text,
  state text,
  date_of_birth date,
  airport_miles text,
  height text,
  walk_around_weight numeric,
  weight_class text,
  fighter_level text check (fighter_level in ('Amateur','Professional')),
  disciplines text[],
  amateur_record text,
  years_experience numeric,
  availability text,
  fighting_background text,
  has_bloodwork text,
  bloodwork_completed_date date,
  highlight_link text,
  status text not null default 'new',
  created_at timestamptz not null default now()
);


create table if not exists public.team_applications (
  id bigint generated by default as identity primary key,
  netlify_submission_id text unique, full_name text, email text, phone text, city text, state text, position text, experience text, portfolio text, instagram text, youtube text, resume_url text, work_samples_url text, about_yourself text, why_join_ctc text, volunteer_confirmation text, status text not null default 'new', submission_data jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.sponsor_inquiries (
  id bigint generated by default as identity primary key,
  netlify_submission_id text unique, contact_name text, company_name text, email text, phone text, website text, social_handle text, sponsorship_type text, budget text, about_brand text, what_to_sponsor text, partner_goals text, brand_materials_url text, contact_agreement text, status text not null default 'new', submission_data jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table public.applications add column if not exists fighter_level text;

-- 2) Security helper
create or replace function public.is_ctc_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users where user_id = auth.uid()
  );
$$;

grant execute on function public.is_ctc_admin() to anon, authenticated;

-- 3) RLS
alter table public.admin_users enable row level security;
alter table public.events enable row level security;
alter table public.gallery_items enable row level security;
alter table public.site_settings enable row level security;
alter table public.applications enable row level security;
alter table public.team_applications enable row level security;
alter table public.sponsor_inquiries enable row level security;

-- Drop old policy versions so this file can be rerun safely
drop policy if exists "Public can read published events" on public.events;
drop policy if exists "Admins manage events" on public.events;
drop policy if exists "Public can read published gallery" on public.gallery_items;
drop policy if exists "Admins manage gallery" on public.gallery_items;
drop policy if exists "Public can read site settings" on public.site_settings;
drop policy if exists "Admins manage site settings" on public.site_settings;
drop policy if exists "Admins can view admin list" on public.admin_users;
drop policy if exists "Public submit applications" on public.applications;
drop policy if exists "Admins manage applications" on public.applications;

create policy "Public can read published events"
on public.events for select to anon, authenticated
using (is_published = true or public.is_ctc_admin());

create policy "Admins manage events"
on public.events for all to authenticated
using (public.is_ctc_admin())
with check (public.is_ctc_admin());

create policy "Public can read published gallery"
on public.gallery_items for select to anon, authenticated
using (is_published = true or public.is_ctc_admin());

create policy "Admins manage gallery"
on public.gallery_items for all to authenticated
using (public.is_ctc_admin())
with check (public.is_ctc_admin());

create policy "Public can read site settings"
on public.site_settings for select to anon, authenticated
using (true);

create policy "Admins manage site settings"
on public.site_settings for all to authenticated
using (public.is_ctc_admin())
with check (public.is_ctc_admin());

create policy "Admins can view admin list"
on public.admin_users for select to authenticated
using (user_id = auth.uid() or public.is_ctc_admin());

create policy "Public submit applications"
on public.applications for insert to anon, authenticated
with check (true);

create policy "Admins manage applications"
on public.applications for all to authenticated
using (public.is_ctc_admin())
with check (public.is_ctc_admin());


drop policy if exists "Admins manage team applications" on public.team_applications;
drop policy if exists "Admins manage sponsor inquiries" on public.sponsor_inquiries;
create policy "Admins manage team applications" on public.team_applications for all to authenticated using (public.is_ctc_admin()) with check (public.is_ctc_admin());
create policy "Admins manage sponsor inquiries" on public.sponsor_inquiries for all to authenticated using (public.is_ctc_admin()) with check (public.is_ctc_admin());

-- 4) Public media bucket and upload policies
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'ctc-media',
  'ctc-media',
  true,
  10485760,
  array['image/jpeg','image/png','image/webp','image/gif']
)
on conflict (id) do update
set public = true,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public read CTC media" on storage.objects;
drop policy if exists "Admins upload CTC media" on storage.objects;
drop policy if exists "Admins update CTC media" on storage.objects;
drop policy if exists "Admins delete CTC media" on storage.objects;

create policy "Public read CTC media"
on storage.objects for select to public
using (bucket_id = 'ctc-media');

create policy "Admins upload CTC media"
on storage.objects for insert to authenticated
with check (bucket_id = 'ctc-media' and public.is_ctc_admin());

create policy "Admins update CTC media"
on storage.objects for update to authenticated
using (bucket_id = 'ctc-media' and public.is_ctc_admin())
with check (bucket_id = 'ctc-media' and public.is_ctc_admin());

create policy "Admins delete CTC media"
on storage.objects for delete to authenticated
using (bucket_id = 'ctc-media' and public.is_ctc_admin());

-- 5) Seed the exact content already on the website, only when empty
insert into public.events
  (promotion, event_date, city, state, venue, status, sort_order, is_published)
select * from (values
  ('Combat Night', date '2026-08-08', 'Kissimmee', 'FL', 'Osceola Heritage Park', 'confirmed', 1, true),
  ('Flex Fighting Series', date '2026-09-12', 'New York', 'NY', 'Melrose Ballroom', 'matching', 2, true),
  ('Flex Fighting Series', date '2026-09-24', 'New York', 'NY', 'Madison Square Garden', 'matching', 3, true),
  ('TBD', date '2026-10-24', 'Location', 'TBD', 'Location TBD', 'planning', 4, true)
) as seed(promotion, event_date, city, state, venue, status, sort_order, is_published)
where not exists (select 1 from public.events);

insert into public.gallery_items
  (image_url, caption, alt_text, sort_order, is_featured, is_published)
select
  'assets/gallery/ctc-family-' || lpad(n::text, 2, '0') || '.webp',
  null,
  'CTC Family photo ' || n,
  n,
  (n = 1),
  true
from generate_series(1,14) as n
where not exists (select 1 from public.gallery_items);

insert into public.site_settings (setting_key, setting_value)
values
  ('home_eyebrow', 'FIGHT OPPORTUNITIES'),
  ('home_line1', 'GET OFF THE COUCH'),
  ('home_line2', 'INTO THE CAGE'),
  ('home_description', 'Join the Couch To Cage roster and get connected with MMA, Muay Thai, and kickboxing opportunities.'),
  ('fighter_count', '30+'),
  ('homepage_announcement', ''),
  ('contact_email', 'Officialcouchtocage@gmail.com'),
  ('instagram_url', 'https://www.instagram.com/couchtocage_/'),
  ('tiktok_url', 'https://www.tiktok.com/@couchtocage'),
  ('twitch_url', 'https://m.twitch.tv/couchtocage/home'),
  ('contact_intro', 'Whether you are a fighter ready to get off the couch and make your mark, or a promoter seeking dependable amateur or professional talent, we want to hear from you.'),
  ('map_locations', '[{"name":"Las Vegas","x":264,"y":579},{"name":"Seattle","x":132,"y":102},{"name":"Los Angeles","x":142,"y":648},{"name":"Dallas","x":774,"y":735},{"name":"Chicago","x":986,"y":399},{"name":"Atlanta","x":1143,"y":661},{"name":"Miami","x":1316,"y":901},{"name":"New York","x":1349,"y":381}]'),
  ('promotions', '[{"name":"Flex Fight Series","logo_url":"assets/partners/flex-fight-series.webp","sort_order":1},{"name":"Combat Night","logo_url":"assets/partners/combat-night.webp","sort_order":2},{"name":"Tuff-N-Uff","logo_url":"assets/partners/tuff-n-uff.webp","sort_order":3}]')
on conflict (setting_key) do nothing;

-- 6) Ensure the official account is approved if it already exists in Auth
insert into public.admin_users (user_id, email)
select id, email from auth.users
where lower(email) = lower('officialcouchtocage@gmail.com')
on conflict (user_id) do update set email = excluded.email;

-- Finished
select 'CTC Control Center setup complete' as result;
