import {supabase} from '../js/supabase-config.js';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
let mode='signin',state=null;
const status=(t,auth=false)=>{(auth?$('authStatus'):$('globalStatus')).textContent=t||''};
const link=v=>{try{const u=new URL(v);return u.protocol==='https:'?u.href:''}catch{return ''}};
async function api(action,body){const {data:{session}}=await supabase.auth.getSession();if(!session)throw Error('Sign in first');const r=await fetch('/.netlify/functions/ctc-team-api?action='+encodeURIComponent(action),{method:body?'POST':'GET',headers:{Authorization:'Bearer '+session.access_token,...(body?{'content-type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,cache:'no-store'});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||`Request failed (${r.status})`);return j}
const show=(signed)=>{$('auth').hidden=signed;$('app').hidden=!signed;$('signout').hidden=!signed};
function switchMode(value){mode=value;for(const [i,x] of [['showSignIn','signin'],['showActivate','activate'],['showRecover','recover']])$(i).setAttribute('aria-selected',String(x===mode));$('passwordLabel').hidden=value==='recover';$('passwordLabel').querySelector('input').required=value!=='recover';$('authSubmit').textContent=value==='activate'?'CREATE MY ACCOUNT':value==='recover'?'SEND PASSWORD RESET':'SIGN IN';status('',true)}
for(const [i,x] of [['showSignIn','signin'],['showActivate','activate'],['showRecover','recover']])$(i).onclick=()=>switchMode(x);
$('authForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,email=form.elements.email.value.trim(),password=form.elements.password.value;status('Please wait…',true);try{if(mode==='recover'){const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:location.origin+'/coach-portal/'});if(error)throw error;status('Check your email for the reset link.',true);return}const {data,error}=mode==='activate'?await supabase.auth.signUp({email,password,options:{emailRedirectTo:location.origin+'/coach-portal/'}}):await supabase.auth.signInWithPassword({email,password});if(error)throw error;if(mode==='activate'&&!data.session){status('Check your email and verify your account, then sign in.',true);return}await load()}catch(err){status(err.message,true)}};
async function load(){try{const info=await api('bootstrap');if(!info.staff){show(false);status('Your email is not yet linked to an approved CTC Coach/Team account. Please contact Management.',true);return}show(true);$('welcome').textContent=`Welcome, ${info.staff.first_name}`;await refresh()}catch(e){show(false);status(e.message,true)}}
async function refresh(){status('Refreshing live CTC information…');try{state=await api('my-dashboard');render();status('Updated '+new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit'}))}catch(e){status(e.message)}}
function render(){const fights=state.matches||[],people=state.fighters||[];const sharedTravel=new Map((state.fighterTravel||[]).map(t=>[t.matchup_id,t]));const groups=new Map();for(const f of fights){const k=[f.fight_date,f.event_name||f.promotion].join('|');if(!groups.has(k))groups.set(k,[]);groups.get(k).push(f)}$('cardList').innerHTML=[...groups].map(([k,rows])=>`<article class="tile"><span class="eye">${esc(rows[0].fight_date)}</span><h3>${esc(rows[0].event_name||rows[0].promotion||'Fight Card')}</h3>${rows.map(m=>{const f=people.find(x=>x.id===m.fighter_id);return `<p>${esc([f?.first_name,f?.last_name].filter(Boolean).join(' ')||'Assigned fighter')}${m.opponent_name?' vs '+esc(m.opponent_name):''}</p>${sharedTravel.has(m.id)?(()=>{const t=sharedTravel.get(m.id);return `<p class="muted">Fighter travel: ${esc(t.carrier||t.mode||'Travel')} · ${esc(t.depart_from||'TBA')} → ${esc(t.arrive_at||'TBA')} · ${esc(t.departure_at||'Time TBA')}</p>${link(t.travel_url)?`<p><a href="${esc(link(t.travel_url))}" target="_blank" rel="noopener">OPEN CARRIER ↗</a></p>`:''}`})():''}`}).join('')}</article>`).join('')||'<p class="muted">No cards assigned yet. CTC Management can assign an individual fighter, an entire card or the full roster.</p>';
$('fighterList').innerHTML=people.map(f=>`<article class="tile"><span class="eye">CTC FIGHTER</span><h3>${esc([f.first_name,f.last_name].filter(Boolean).join(' '))}</h3>${f.current_weight!=null?`<p><strong>Current weight:</strong> ${esc(f.current_weight)} lb</p>`:''}${f.target_weight!=null?`<p><strong>Fight weight:</strong> ${esc(f.target_weight)} lb</p>`:''}${f.weight_class?`<p><strong>Class:</strong> ${esc(f.weight_class)}</p>`:''}${f.gym?`<p><strong>Gym:</strong> ${esc(f.gym)}</p>`:''}${link(f.tapology_url)?`<p><a href="${esc(link(f.tapology_url))}" target="_blank" rel="noopener">OPEN TAPOLOGY ↗</a></p>`:''}<div class="actions"><button data-weight="${esc(f.id)}">REQUEST WEIGHT</button></div></article>`).join('')||'<p class="muted">No fighters assigned yet.</p>';
$('travelList').innerHTML=(state.travel||[]).map(t=>`<article class="tile"><span class="eye">${esc(t.event_date)} · ${esc(t.mode)}</span><h3>${esc(t.carrier||'CTC Travel')}</h3>${t.service_number?`<p>Trip # ${esc(t.service_number)}</p>`:''}<p>${esc(t.depart_from||'Departure TBA')} → ${esc(t.arrive_at||'Arrival TBA')}</p><p>${esc(t.departure_at||'Departure time TBA')}</p>${t.notes?`<p>${esc(t.notes)}</p>`:''}${link(t.travel_url)?`<a href="${esc(link(t.travel_url))}" rel="noopener" target="_blank">OPEN CARRIER ↗</a>`:''}</article>`).join('')||'<p class="muted">No travel itinerary assigned yet.</p>';
$('messagesList').innerHTML=(state.messages||[]).map(m=>`<div class="bubble ${m.sender_role==='personnel'?'mine':''}"><small>${m.sender_role==='personnel'?'YOU':'CTC MANAGEMENT'} · ${new Date(m.created_at).toLocaleString()}</small><br>${esc(m.body)}</div>`).join('')||'<p class="muted">Send CTC Management a message.</p>';
$('leaveList').innerHTML=(state.leaves||[]).map(l=>`<article class="tile"><strong>${esc(l.start_date)} → ${esc(l.return_date)}</strong>${l.reason?`<p>${esc(l.reason)}</p>`:''}${l.start_date<=new Date().toISOString().slice(0,10)&&l.return_date>=new Date().toISOString().slice(0,10)?'<span class="pill">ON LEAVE</span>':''}</article>`).join('')||'<p class="muted">No leave history.</p>';
}
$('fighterList').onclick=async e=>{const b=e.target.closest('[data-weight]');if(!b)return; if(!confirm('Request a new weigh-in from this assigned fighter?'))return;b.disabled=true;try{const r=await api('request-weight',{fighter_id:b.dataset.weight});status(r.already_pending?'This fighter already has a pending weight request.':'Weight request sent to their Fighter Portal.')}catch(err){status(err.message)}finally{b.disabled=false}};
$('messageForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,msg=f.elements.message.value;try{await api('my-message',{message:msg});f.reset();await refresh();document.getElementById('messagesList').scrollTop=99999}catch(err){status(err.message)}};
$('leaveForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{await api('my-leave',{start_date:f.elements.start_date.value,return_date:f.elements.return_date.value,reason:f.elements.reason.value});f.reset();await refresh();status('CTC Management can now see your leave dates.')}catch(err){status(err.message)}};
$('tabs').onclick=e=>{const b=e.target.closest('[data-tab]');if(!b)return;for(const tab of document.querySelectorAll('#tabs [data-tab]'))tab.setAttribute('aria-selected',String(tab===b));for(const section of document.querySelectorAll('.tab'))section.hidden=section.id!==b.dataset.tab};
$('refresh').onclick=refresh;$('signout').onclick=async()=>{await supabase.auth.signOut();state=null;show(false);status('',true)};
supabase.auth.onAuthStateChange((event)=>{if(event==='SIGNED_OUT'){show(false);state=null}});
const {data:{session}}=await supabase.auth.getSession();if(session)await load();else show(false);
