import {supabase} from '../js/supabase-config.js';
const $=id=>document.getElementById(id);let current=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const attachmentLink=m=>m.attachment_path&&m.attachment_name?`<button class="ctc-attachment" type="button" data-ctc-attachment="${esc(m.id)}">📎 ${esc(m.attachment_name)}</button>`:'';
async function openAttachment(id){const tab=window.open('about:blank','_blank');try{const {data:{session}}=await supabase.auth.getSession();if(!session)throw Error('Sign in to open attachments');const res=await fetch(`/.netlify/functions/ctc-message-attachments?action=open&message_id=${encodeURIComponent(id)}`,{headers:{Authorization:`Bearer ${session.access_token}`}});const json=await res.json();if(!res.ok)throw Error(json.error||'Attachment unavailable');if(tab)tab.location.href=json.url;else location.href=json.url}catch(err){if(tab)tab.close();const status=document.getElementById('ctcAdminMessageStatus')||document.getElementById('ctcFighterMessageStatus');if(status)status.textContent=err.message}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-ctc-attachment]');if(b){e.preventDefault();openAttachment(b.dataset.ctcAttachment)}});
const fileToBase64=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]||'');reader.onerror=()=>reject(Error('Could not read file'));reader.readAsDataURL(file)});
async function sendAttachment({fighter_id,body,file}){if(file.size>3*1024*1024)throw Error('Attachment must be 3 MB or less');const {data:{session}}=await supabase.auth.getSession();if(!session)throw Error('Sign in to send attachments');const resp=await fetch('/.netlify/functions/ctc-message-attachments?action=send',{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({fighter_id,body,file:{name:file.name,type:file.type,base64:await fileToBase64(file)}})});const out=await resp.json();if(!resp.ok)throw Error(out.error||'Attachment failed');return out}
async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data:f,error:fe}=await supabase.from('fighters').select('id').eq('auth_user_id',user.id).maybeSingle();if(fe||!f)return;current=f.id;const {data,error}=await supabase.from('ctc_messages').select('*').eq('fighter_id',current).order('created_at');if(error){$('ctcFighterMessageStatus').textContent=error.message;return}const unread=(data||[]).filter(m=>m.sender_role==='admin'&&!m.read_at);$('ctcFighterUnread').textContent=unread.length?`(${unread.length})`:'';$('ctcFighterConversation').innerHTML=(data||[]).map(m=>`<div class="ctc-bubble ${m.sender_role==='fighter'?'mine':''}"><div>${esc(m.body).replace(/\n/g,'<br>')}</div>${attachmentLink(m)}<small>${m.sender_role==='fighter'?'You':'CTC'} · ${new Date(m.created_at).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</small></div>`).join('')||'<p class="muted">No messages yet. Send CTC a message below.</p>';if(unread.length){await supabase.from('ctc_messages').update({read_at:new Date().toISOString()}).in('id',unread.map(m=>m.id));$('ctcFighterUnread').textContent=''}}
$('ctcFighterMessageForm').onsubmit=async e=>{e.preventDefault();if(!current)return;const body=$('ctcFighterMessageText').value.trim(),file=$('ctcFighterMessageFile').files?.[0];if(!body&&!file)return;let error=null;try{if(file)await sendAttachment({fighter_id:current,body,file});else({error}=await supabase.from('ctc_messages').insert({fighter_id:current,sender_role:'fighter',body}));}catch(e){error=e;}$('ctcFighterMessageStatus').textContent=error?error.message:'';if(!error){$('ctcFighterMessageText').value='';$('ctcFighterMessageFile').value='';await load();$('ctcFighterConversation').scrollTop=$('ctcFighterConversation').scrollHeight}};
supabase.auth.onAuthStateChange((event)=>{if(event==='SIGNED_IN')setTimeout(load,500);if(event==='SIGNED_OUT')current=null});setTimeout(load,700);document.querySelector('[data-tab="messages"]')?.addEventListener('click',load);

document.addEventListener('visibilitychange',()=>{if(!document.hidden&&current)load()});
